apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  releaseName: cilium
  chart:
    spec:
      chart: cilium
      version: "1.18.3" 
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
  interval: 2m
  values:
    autoDirectNodeRoutes: true
    bpf:
      datapathMode: netkit
      masquerade: true
    cluster:
      name: ""
    devices:
      - eth0
    enableIPv4Masquerade: true
    enableIPv6Masquerade: true
    extraArgs:
      - --devices=ens+
    eni:
      enabled: true
    routingMode: native

    hubble:
      enabled: true
      relay:
        enabled: true
        tolerations:
          - effect: NoSchedule
            key: node-type
            operator: Equal
            value: core
      ui:
        enabled: true
        tolerations:
          - effect: NoSchedule
            key: node-type
            operator: Equal
            value: core
    image:
      repository: quay.io/cilium/cilium
      tag: v1.16.4
    ipam:
      eni:
        enabled: true
        securityGroupTags: {}
        subnetTags: {}
      mode: eni
    k8sServiceHost: ${CLUSTER_ENDPOINT}
    k8sServicePort: 443
    kubeProxyReplacement: true
    loadBalancer:
      algorithm: maglev
      mode: dsr
    nodePort:
      enabled: true
    operator:
      image:
        repository: quay.io/cilium/operator
        tag: v1.16.4
      prometheus:
        enabled: true
      replicas: 1
      tolerations:
        - effect: NoSchedule
          key: node-type
          operator: Equal
          value: core
    prometheus:
      enabled: true


