apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local-path-storage
resources:
  - ../../../../../iac-modules/extensions/namespace/v1/
  - ../../../../../iac-modules/extensions/local-path-provisioner/v0.0.30-v1/
