apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-instance
  namespace: flux-system
spec:
  releaseName: flux-instance
  chart:
    spec:
      chart: flux-instance
      version: "0.33.0"
      sourceRef:
        kind: HelmRepository
        name: flux-instance
        namespace: flux-instance
  interval: 2m
  values:
    instance:
      components:
      - source-controller
      - kustomize-controller
      - helm-controller
      - notification-controller
      - image-reflector-controller
      - image-automation-controller
    kustomize:
      patches:
      - target:
          kind: Deployment
        patch: |
          - op: replace
            path: /spec/template/spec/nodeSelector
            value:
              kubernetes.io/os: linux
          - op: add
            path: /spec/template/spec/tolerations
            value:
              - key: "CriticalAddonsOnly"
                operator: "Exists"
    sync:
      kind: GitRepository
      ref: "refs/heads/main"
      path: "clusters/prod/extensions"
      pullSecret: "flux-git-creds"
      url: "https://github.com/hrishin/eks-pulumi.git"
    
