apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluxcd
  namespace: flux-system
spec:
  releaseName: fluxcd
  chart:
    spec:
      chart: flux2
      version: "2.17.1" 
      sourceRef:
        kind: HelmRepository
        name: fluxcd
        namespace: flux-system
  interval: 1m
  values:
    installCRDs: true
    notificationController:
      resources:
        limits:
          memory: 170Mi
        requests:
          memory: 170Mi
      tolerations:
        - key: node-type
          operator: Equal
          value: core
          effect: NoSchedule
      nodeSelector:
        node-type: core
    sourceController:
      resources:
        limits:
          memory: 170Mi
        requests:
          memory: 170Mi
      tolerations:
        - key: node-type
          operator: Equal
          value: core
          effect: NoSchedule
      nodeSelector:
        node-type: core
    sourceWatcher:
      resources:
        limits:
          memory: 170Mi
        requests:
          memory: 170Mi
      tolerations:
        - key: node-type
          operator: Equal
          value: core
          effect: NoSchedule
      nodeSelector:
        node-type: core
    kustomizeController:
      resources:
        limits:
          memory: 170Mi
        requests:
          memory: 170Mi
      tolerations:
        - key: node-type
          operator: Equal
          value: core
          effect: NoSchedule
      nodeSelector:
        node-type: core
    imageReflectionController:
      resources:
        limits:
          memory: 170Mi
        requests:
          memory: 170Mi
      tolerations:
        - key: node-type
          operator: Equal
          value: core
          effect: NoSchedule
      nodeSelector:
        node-type: core
    imageAutomationController:
      resources:
        limits:
          memory: 170Mi
        requests:
          memory: 170Mi
      tolerations:
        - key: node-type
          operator: Equal
          value: core
          effect: NoSchedule
      nodeSelector:
        node-type: core
    helmController:
      resources:
        limits:
          memory: 170Mi
        requests:
          memory: 170Mi
      tolerations:
        - key: node-type
          operator: Equal
          value: core
          effect: NoSchedule
      nodeSelector:
        node-type: core
    cli:
      tolerations:
        - key: node-type
          operator: Equal
          value: core
          effect: NoSchedule
      nodeSelector:
        node-type: core
