apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluxcd
  namespace: flux-system
spec:
  releaseName: fluxcd
  chart:
    spec:
      chart: fluxcd
      version: "2.7.0" 
      sourceRef:
        kind: HelmRepository
        name: fluxcd
        namespace: flux-system
  interval: 2m
  values:
    notificationController:
      resources:
        limits:
          memory: 170Mi
        requests:
          memory: 170Mi
      tolerations:
      - key: node-type
        operator: Equal
        value: core
        effect: NoSchedule
    sourceController:
      resources:
        limits:
          memory: 170Mi
        requests:
          memory: 170Mi
      tolerations:
      - key: node-type
        operator: Equal
        value: core
        effect: NoSchedule
    sourceWatcher:
      resources:
        limits:
          memory: 170Mi
        requests:
          memory: 170Mi
      tolerations:
      - key: node-type
        operator: Equal
        value: core
        effect: NoSchedule
    kustomizeController:
      resources:
        limits:
          memory: 170Mi
        requests:
          memory: 170Mi
      tolerations:
      - key: node-type
        operator: Equal
        value: core
        effect: NoSchedule
    imageReflectionController:
      resources:
        limits:
          memory: 170Mi
        requests:
          memory: 170Mi
      tolerations:
      - key: node-type
        operator: Equal
        value: core
        effect: NoSchedule
    imageAutomationController:
      resources:
        limits:
          memory: 170Mi
        requests:
          memory: 170Mi
      tolerations:
      - key: node-type
        operator: Equal
        value: core
        effect: NoSchedule
    helmController:
      resources:
        limits:
          memory: 170Mi
        requests:
          memory: 170Mi
      tolerations:
      - key: node-type
        operator: Equal
        value: core
        effect: NoSchedule
