apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repo.yaml
  - secret-kibana-prerequisites.yaml
  - release-elasticsearch.yaml
  - release-kibana.yaml
  - httproutes.yaml
