apiVersion: v1
kind: Secret
metadata:
  name: kibana-kibana-es-token
  namespace: logging
type: Opaque
stringData:
  token: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-master-certs
  namespace: logging
type: Opaque
data: {}
