apiVersion: v1
kind: Secret
metadata:
  name: kibana-kibana-es-token
  namespace: logging
type: Opaque
stringData:
  token: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-master-certs
  namespace: logging
type: Opaque
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIVENDQWdXZ0F3SUJBZ0lVSzcyaXZackVPckI2bi8wTlBaa2dBMHdxMXM4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0hqRWNNQm9HQTFVRUF3d1RaV3hoYzNScFkzTmxZWEpqYUMxa2RXMXRlVEFlRncweU5qQTFNRFF4TnpBNApNemxhRncwek5qQTFNREV4TnpBNE16bGFNQjR4SERBYUJnTlZCQU1NRTJWc1lYTjBhV056WldGeVkyZ3RaSFZ0CmJYa3dnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEY2p1ZldZZ3gyNkxDYzRWVXoKcjFaUHhwczlWTFJpd3J4UXpqOEhXTUlkR0FrOGFNT21QNStzbWJ6M2kyczRNT3JQZzVMV2pPVlZlekxVWnVWSQpDTXU3NHdaMXBGL3RqY2tPbUdGZTQ5VTRNd0Q2RTlZU3cwS0VwSlJ0MVo4VHB3cjcwT3lpWnJxcjU1anUvcDZHCi9OdCtqaFZZZTZqQUt1Z2M5NUhGUVRJMjk2Mnp3SjIzN1RsbVB6THRTNjRLbzRMQ3ozdFk2aWhPbDM2dzhEdS8KNjh5QU0zMFpDY2dxbUNIbmxpc3FUbUtsNEFTdTZDVENqQ0wycXJpZDNmZzZEbVJldTc1Nm1meWd3ZmtvU2xJVQpLSmFpN1RYVURFKzhMVXp6NUJXdG9VQnh3T0dvNVZRRjZjZkZhL2NRWVc0WVBlcWNIRmp2Ym5zWW9aVTB3ZlVnCkluaUhBZ01CQUFHalV6QlJNQjBHQTFVZERnUVdCQlJqYkZ4KzB1Z1JicHFNRlNhb0RxMCtucUdKVURBZkJnTlYKSFNNRUdEQVdnQlJqYkZ4KzB1Z1JicHFNRlNhb0RxMCtucUdKVURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0FLbzJkcEJnejJjTmpJSzhaY1RVSUdJWmMvTitPM2NydFFNSisrb3pKClVQcUJpMDRRWXFaWWxXR0xaSldwYjhYYUszV2k2Y3I4N3V4Q3VxbHRNZkswWHBZajZ2R0Y1cFNvSW54NFAyMkMKQWFQaEwyRU1hTkZMSncwT25vTzN5eGx6YThuQ1c3c3NIdnVmWWh6dHBzalFUQW9LSzY4WjVBTW5oQ2o4TkZsTwpoTGh6S3JKYm9aRm82dmw2V0ZzTEhGUWVDVUFxWlBKaXJncEEwOG5Nakk4c1lpbE1LbjhqdUNZSStISk4vSHkzCksxa1FYc3EzMFZRMCtUMTJ3SXJ0RVpwSDExL2VDWGJIclJYOHR1bXdKMGhieVdXdUthRmxDcU55ejhENUhZVW4KWUdieVdVQ0d4ZmFBOVljb05KaW5mZHhqR3oxWU9nWTFnTm5CSSsxUXVhdFMKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
