github:
    username: ENC[AES256_GCM,data:dKcOUNbCkA==,iv:iZuKr8NFAotrImaRTFdWiY2kFI1TyTjui4RRjKMRXcY=,tag:Gzt7TsDRC1NW183qqBvBXA==,type:str]
    token: ENC[AES256_GCM,data:yis9DmURTm41JRxu3VJNG+Z05ynOpnKybawpTlP5EToPuPnZOjRslg==,iv:eRxq0/4a3RhVjlo0ODWm0Lm/CX6W6u92uUMdtkrlddY=,tag:OEvwHlqv1yWPQXRtbOWRjA==,type:str]
sops:
    age:
        - recipient: age1ppc0g76en84sppjk7qxljz75wkdvryj87q852pmxuw8k8cwxevqsgpwz3l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNDVTeThNUklMWm9OU0pY
            WFlUVWVxd2R0K1dDRTVYSmtITk5QY2RhZVNVCnlZWTE5T0xaTGx2UTVoRUpDaDlT
            WVhrMU1xdjJBUytlK2IzV2I4M1VRMXcKLS0tIHlYYmYvNXZmSERCcWtwS0JpVk9j
            WHMrNXF4a2dUVG4rbllyMVIzait1aUkKfE1gbaibYzMiYGseNFlVj7Vl6bsiiwsG
            UeFR0qi/p8+SjQ9Xwp1nxw/mv+CFNMOPVx/RRQLKJP7nYZOU2CD6kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T14:19:33Z"
    mac: ENC[AES256_GCM,data:ssqxf3JSvPJfXk1ZvtDEm39Hpu2cn2KHb2GFSoektOWTkOvxrg/MLgG4awu4fdpIl++gwGpjyWVeptzpiOs5+9/rmT2qeR+LwmMZ7+BuOc0EzzSKvtf11coeAHzeSiPuVqgno6+LfYlEUNd9pi1nOAhZHTAyhrjWjQGOs47Len4=,iv:YNFVMAkBrB0KAaaEgDBI3iW1/GfsN3u9KqDcN6MXicU=,tag:JQHr9Fby1onrgwjyOK/nzA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
