apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flux-operator
  namespace: flux-operator
spec:
  interval: 20m
  type: oci
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator
