autoDirectNodeRoutes: true
bpf:
  datapathMode: netkit
  masquerade: true
cluster:
  name: ""
enableIPv4Masquerade: true
enableIPv6Masquerade: true
# --- ENI IPAM mode (commented out) ---
# eni:
#   enabled: true
#   awsEnablePrefixDelegation: true
routingMode: native

hubble:
  enabled: true
  relay:
    enabled: true
    tolerations:
      - effect: NoSchedule
        key: node-type
        operator: Equal
        value: core
  ui:
    enabled: true
    tolerations:
      - effect: NoSchedule
        key: node-type
        operator: Equal
        value: core
image:
  repository: quay.io/cilium/cilium
  tag: v1.16.4
# --- ENI IPAM configuration (commented out) ---
# ipam:
#   eni:
#     enabled: true
#     securityGroupTags: {}
#     subnetTags: {}
#   mode: eni

# --- Cluster Scope IPAM mode ---
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList:
      - 192.168.0.0/16
    clusterPoolIPv4MaskSize: 24
k8sServiceHost: ""
k8sServicePort: 443
kubeProxyReplacement: true
loadBalancer:
  algorithm: maglev
  mode: dsr
nodePort:
  enabled: true
operator:
  image:
    repository: quay.io/cilium/operator
    tag: v1.16.4
  prometheus:
    enabled: true
  replicas: 1
  tolerations:
    - effect: NoSchedule
      key: node-type
      operator: Equal
      value: core
prometheus:
  enabled: true

