apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: system
  namespace: flux-system
spec:
  interval: 1m50s
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/prod/infra/extensions/system/
  prune: true
  wait: true
  dependsOn:
  - name: infra
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: infra-outputs
      optional: false