apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: gateway-api
  namespace: kgateway-system
spec:
  interval: 1h
  url: https://github.com/kubernetes-sigs/gateway-api
  ref:
    tag: v1.4.0
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gateway-api-crds
  namespace: kgateway-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: gateway-api
  path: ./config/crd
  prune: true
  wait: true
