apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kgateway-hostnetwork-crs
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./iac-modules/extensions/kgateway/v2.3.0-v1/crs
  prune: true
  wait: true
